# Numpy, Matplotlib and Sklearn Tutorial


We often use numpy to handle high dimensional arrays.

Let's try the basic operation of numpy:

In [1]:
import numpy as np

a = np.array([[1,2,3], [2,3,4]])
print(a.ndim, a.shape, a.size, a.dtype, type(a),'\n')

b = np.zeros((3,4))
c = np.ones((3,4))
d = np.random.randn(2,3)
e = np.array([[1,2], [2,3], [3,4]])
f = b*2 - c*3
g = 2*c*f
h = np.dot(a,e)
i = d.mean()
j = d.max(axis=1)
k = a[-1][:2]

# You can print a to k for details
test = [b,c,d,e,f,g,h,i,j,k]
for i in test:
    print(i,'\n')

2 (2, 3) 6 int64 <class 'numpy.ndarray'> 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[-0.42265306 -1.97095138  1.26588055]
 [ 1.06018736 -0.17613411 -0.10353789]] 

[[1 2]
 [2 3]
 [3 4]] 

[[-3. -3. -3. -3.]
 [-3. -3. -3. -3.]
 [-3. -3. -3. -3.]] 

[[-6. -6. -6. -6.]
 [-6. -6. -6. -6.]
 [-6. -6. -6. -6.]] 

[[14 20]
 [20 29]] 

-0.05786808917056505 

[1.26588055 1.06018736] 

[2 3] 



matplotlib.pyplot provides very useful apis for drawing graphs.

Let's try the basic operation of matplotlib.pyplot:

In [2]:
import matplotlib.pyplot as plt

x = np.arange(2, 10, 0.2)

plt.plot(x, x**1.5*.5, 'r-', x, np.log(x)*5, 'g--', x, x, 'b.')
plt.show()

<Figure size 640x480 with 1 Axes>